# Generated by Django 5.1.1 on 2024-10-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Childs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoeName', models.CharField(max_length=100)),
                ('shoeDescription', models.CharField(max_length=100)),
                ('shoePrice', models.FloatField()),
                ('shoeStock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoeName', models.CharField(max_length=100)),
                ('shoeDescription', models.CharField(max_length=100)),
                ('shoePrice', models.FloatField()),
                ('shoeStock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Woman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoeName', models.CharField(max_length=100)),
                ('shoeDescription', models.CharField(max_length=100)),
                ('shoePrice', models.FloatField()),
                ('shoeStock', models.IntegerField()),
            ],
        ),
    ]
