# Generated by Django 5.1.1 on 2024-10-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_childs_men_woman'),
    ]

    operations = [
        migrations.AddField(
            model_name='childs',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='men',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='woman',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
