# Generated by Django 5.1.1 on 2024-10-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_childs_image_url_men_image_url_woman_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childs',
            old_name='shoeDescription',
            new_name='shoe_description',
        ),
        migrations.RenameField(
            model_name='childs',
            old_name='shoeName',
            new_name='shoe_name',
        ),
        migrations.RenameField(
            model_name='childs',
            old_name='shoePrice',
            new_name='shoe_price',
        ),
        migrations.RenameField(
            model_name='childs',
            old_name='shoeStock',
            new_name='shoe_stock',
        ),
        migrations.RenameField(
            model_name='men',
            old_name='shoeDescription',
            new_name='shoe_description',
        ),
        migrations.RenameField(
            model_name='men',
            old_name='shoeName',
            new_name='shoe_name',
        ),
        migrations.RenameField(
            model_name='men',
            old_name='shoePrice',
            new_name='shoe_price',
        ),
        migrations.RenameField(
            model_name='men',
            old_name='shoeStock',
            new_name='shoes_tock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productName',
            new_name='productname',
        ),
        migrations.RenameField(
            model_name='woman',
            old_name='shoeDescription',
            new_name='shoe_description',
        ),
        migrations.RenameField(
            model_name='woman',
            old_name='shoeName',
            new_name='shoe_name',
        ),
        migrations.RenameField(
            model_name='woman',
            old_name='shoePrice',
            new_name='shoe_price',
        ),
        migrations.RenameField(
            model_name='woman',
            old_name='shoeStock',
            new_name='shoe_stock',
        ),
    ]
